require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DosagesController do

  def mock_dosage(stubs={})
    @mock_dosage ||= mock_model(Dosage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all dosages as @dosages" do
      Dosage.stub(:all) { [mock_dosage] }
      get :index
      assigns(:dosages).should eq([mock_dosage])
    end
  end

  describe "GET show" do
    it "assigns the requested dosage as @dosage" do
      Dosage.stub(:find).with("37") { mock_dosage }
      get :show, :id => "37"
      assigns(:dosage).should be(mock_dosage)
    end
  end

  describe "GET new" do
    it "assigns a new dosage as @dosage" do
      Dosage.stub(:new) { mock_dosage }
      get :new
      assigns(:dosage).should be(mock_dosage)
    end
  end

  describe "GET edit" do
    it "assigns the requested dosage as @dosage" do
      Dosage.stub(:find).with("37") { mock_dosage }
      get :edit, :id => "37"
      assigns(:dosage).should be(mock_dosage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created dosage as @dosage" do
        Dosage.stub(:new).with({'these' => 'params'}) { mock_dosage(:save => true) }
        post :create, :dosage => {'these' => 'params'}
        assigns(:dosage).should be(mock_dosage)
      end

      it "redirects to the created dosage" do
        Dosage.stub(:new) { mock_dosage(:save => true) }
        post :create, :dosage => {}
        response.should redirect_to(dosage_url(mock_dosage))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dosage as @dosage" do
        Dosage.stub(:new).with({'these' => 'params'}) { mock_dosage(:save => false) }
        post :create, :dosage => {'these' => 'params'}
        assigns(:dosage).should be(mock_dosage)
      end

      it "re-renders the 'new' template" do
        Dosage.stub(:new) { mock_dosage(:save => false) }
        post :create, :dosage => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dosage" do
        Dosage.stub(:find).with("37") { mock_dosage }
        mock_dosage.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :dosage => {'these' => 'params'}
      end

      it "assigns the requested dosage as @dosage" do
        Dosage.stub(:find) { mock_dosage(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:dosage).should be(mock_dosage)
      end

      it "redirects to the dosage" do
        Dosage.stub(:find) { mock_dosage(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(dosage_url(mock_dosage))
      end
    end

    describe "with invalid params" do
      it "assigns the dosage as @dosage" do
        Dosage.stub(:find) { mock_dosage(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:dosage).should be(mock_dosage)
      end

      it "re-renders the 'edit' template" do
        Dosage.stub(:find) { mock_dosage(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dosage" do
      Dosage.stub(:find).with("37") { mock_dosage }
      mock_dosage.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the dosages list" do
      Dosage.stub(:find) { mock_dosage }
      delete :destroy, :id => "1"
      response.should redirect_to(dosages_url)
    end
  end

end
