require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DrugsController do

  def mock_drug(stubs={})
    @mock_drug ||= mock_model(Drug, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all drugs as @drugs" do
      Drug.stub(:all) { [mock_drug] }
      get :index
      assigns(:drugs).should eq([mock_drug])
    end
  end

  describe "GET show" do
    it "assigns the requested drug as @drug" do
      Drug.stub(:find).with("37") { mock_drug }
      get :show, :id => "37"
      assigns(:drug).should be(mock_drug)
    end
  end

  describe "GET new" do
    it "assigns a new drug as @drug" do
      Drug.stub(:new) { mock_drug }
      get :new
      assigns(:drug).should be(mock_drug)
    end
  end

  describe "GET edit" do
    it "assigns the requested drug as @drug" do
      Drug.stub(:find).with("37") { mock_drug }
      get :edit, :id => "37"
      assigns(:drug).should be(mock_drug)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created drug as @drug" do
        Drug.stub(:new).with({'these' => 'params'}) { mock_drug(:save => true) }
        post :create, :drug => {'these' => 'params'}
        assigns(:drug).should be(mock_drug)
      end

      it "redirects to the created drug" do
        Drug.stub(:new) { mock_drug(:save => true) }
        post :create, :drug => {}
        response.should redirect_to(drug_url(mock_drug))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drug as @drug" do
        Drug.stub(:new).with({'these' => 'params'}) { mock_drug(:save => false) }
        post :create, :drug => {'these' => 'params'}
        assigns(:drug).should be(mock_drug)
      end

      it "re-renders the 'new' template" do
        Drug.stub(:new) { mock_drug(:save => false) }
        post :create, :drug => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested drug" do
        Drug.stub(:find).with("37") { mock_drug }
        mock_drug.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :drug => {'these' => 'params'}
      end

      it "assigns the requested drug as @drug" do
        Drug.stub(:find) { mock_drug(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:drug).should be(mock_drug)
      end

      it "redirects to the drug" do
        Drug.stub(:find) { mock_drug(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(drug_url(mock_drug))
      end
    end

    describe "with invalid params" do
      it "assigns the drug as @drug" do
        Drug.stub(:find) { mock_drug(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:drug).should be(mock_drug)
      end

      it "re-renders the 'edit' template" do
        Drug.stub(:find) { mock_drug(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drug" do
      Drug.stub(:find).with("37") { mock_drug }
      mock_drug.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the drugs list" do
      Drug.stub(:find) { mock_drug }
      delete :destroy, :id => "1"
      response.should redirect_to(drugs_url)
    end
  end

end
